---
title: '`r paste0(params$location, " Sales Report: ", params$year[1], "-", params$year[2])`'
author: "James Blair"
date: '`r Sys.Date()`'
output: html_document
params:
  year: 
    label: "Years:"
    value: [2008, 2018]
    input: slider
    min: 2008
    max: 2018
    step: 1
    sep: ""
  location: 
    label: "Region:"
    choices: ["Global", "North America", "Japan", "Europe", "Other"]
    value: "Global"
---

```{r setup, include=FALSE}
# Packages ----
library(tidyverse)

knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r data}
sales_data <- read_rds("data/vgsales.rds")
```

```{r param-data}
param_data <- sales_data %>% 
  filter(
    Year >= params$year[1],
    Year <= params$year[2],
    Location == params$location
  )
```

## Platform Performance
```{r platform-performance}
param_data %>% 
  group_by(
    Year = as.factor(Year),
    Platform
  ) %>% 
  summarise(
    Sales = sum(Sales, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = Year, y = Sales, col = Platform, group = Platform)) +
  geom_line() +
  labs(title = "Platform Sales") +
  theme_bw()
```


## Genre Performance
```{r}
param_data %>% 
  group_by(
    Year = as.factor(Year),
    Genre
  ) %>% 
  summarise(
    Sales = sum(Sales, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = Year, y = Sales, color = Genre, group = Genre)) +
  geom_line() +
  labs(title = "Genre Sales") +
  theme_bw()
```

